<?php
# automatically generated by makeclasses.php

class ContactsRelation extends Relation {
	function __construct() {
		parent::__construct(
			A3_calDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'PRIMARY KEY' => array ( 'email' => '', 'contact_email' => '', ), 
				'email' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'contact_email' => array ( 'type' => 'varchar', 'size' => 128, ), 
			),
			'contacts'
		);
	}

}
