<?php
# automatically generated by makeclasses.php

class UsersEntity extends Entity {
	function __construct() {
		parent::__construct(
			A3_calDB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'email' => array ( 'type' => 'varchar', 'size' => 128, 'key' => true, ), 
				'name' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'notes' => array ( 'type' => 'text', ), 
			),
			'users'
		);
	}

}
