package catalyst::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Catalyst::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:/var/www/catalyst/books.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys=ON},
    }
);

=head1 NAME

catalyst::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<catalyst>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Catalyst::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

group8

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
