<?php
# automatically generated by makeclasses.php

class LoginEntity extends Entity {
	function __construct() {
		parent::__construct(
			Myv1DB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'email' => array ( 'type' => 'varchar', 'size' => 128, 'key' => true, ), 
				'password' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'user_type' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'external_key' => array ( 'type' => 'int', 'size' => 11, ), 
				'confirmkey' => array ( 'type' => 'varchar', 'size' => 128, ), 
			),
			'Login'
		);
	}

}
