<?php
# automatically generated by makeclasses.php

class AdminEntity extends Entity {
	function __construct() {
		parent::__construct(
			V1DB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'adminID' => array ( 'type' => 'int', 'size' => 11, 'key' => true, 'auto' => 1, ), 
				'permissions' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'created' => array ( 'type' => 'timestamp', ), 
			),
			'Admin'
		);
	}

}
