<?php
# automatically generated by makeclasses.php

class OrganizationEntity extends Entity {
	function __construct() {
		parent::__construct(
			V1DB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'organizationID' => array ( 'type' => 'int', 'size' => 11, 'key' => true, 'auto' => 1, ), 
				'name' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'address' => array ( 'type' => 'text', ), 
				'contact_name_first' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'contact_name_last' => array ( 'type' => 'varchar', 'size' => 64, ), 
				'contact_phone' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'contact_email' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'url' => array ( 'type' => 'varchar', 'size' => 128, ), 
				'visibility_status' => array ( 'type' => 'varchar', 'size' => 32, ), 
				'description' => array ( 'type' => 'text', ), 
				'created' => array ( 'type' => 'timestamp', ), 
			),
			'Organization'
		);
	}

}
