<?php
# automatically generated by makeclasses.php

class ScheduleRelation extends Relation {
	function __construct() {
		parent::__construct(
			V1DB::$db, 
			# $this->schema: for building forms among other things
			array ( 
				'PRIMARY KEY' => array ( 'jobID' => '', 'volunteerID' => '', 'start' => '', ), 
				'jobID' => array ( 'type' => 'int', 'size' => 11, ), 
				'volunteerID' => array ( 'type' => 'int', 'size' => 11, ), 
				'job_date' => array ( 'type' => 'datetime', 'size' => 20, ), 
				'start' => array ( 'type' => 'datetime', ), 
				'hours' => array ( 'type' => 'int', 'size' => 11, ), 
				'hours_worked' => array ( 'type' => 'int', 'size' => 11, ), 
			),
			'Schedule'
		);
	}

}
